In [ ]:
#參考41071134H_PL_HW1

In [ ]:
#匯入CSV
#順德111-11月份與112-2月份時薪表

In [18]:
import pandas as pd
#pandas是處理csv檔案的套件包
#注意:匯入檔案為csv檔的原因是因為乾淨，無須擔心格式問題

Feb = pd.read_csv("data1.csv")
Nov = pd.read_csv("data2.csv")

In [19]:
Feb

          Name                            Date         Subs   完成  時長 課程形式
0   李冠郁_Thomas  2023/02/05 10:30 AM → 12:00 PM   國一, 翰林, 英文  Yes  90  PS1
1   李冠郁_Thomas  2023/02/19 10:30 AM → 12:00 PM  國一, 總複習, 英文  Yes  90  PS1
2   李冠郁_Thomas  2023/02/26 10:30 AM → 12:00 PM  國一, 總複習, 英文  Yes  90  PS1
3   李冠郁_Thomas  2023/02/12 10:30 AM → 12:00 PM  國一, 總複習, 英文  Yes  90  PS1
4          羅英綺    2023/02/05 6:00 PM → 7:30 PM   英文, 高二, 龍騰  Yes  90  PS1
5      鈺淮_Josh    2023/02/20 6:00 PM → 7:30 PM  小學, 總複習, 英文  Yes  90  PS1
6      鈺淮_Josh    2023/02/09 4:40 PM → 6:10 PM  小學, 總複習, 英文  Yes  90  PS1
7      鈺淮_Josh    2023/02/13 6:00 PM → 7:30 PM  小學, 總複習, 英文  Yes  90  PS1
8     黃學承_Matt  2023/02/07 11:00 AM → 12:00 PM   小學, 翰林, 英文  Yes  60  PS1
9     黃學承_Matt    2023/02/12 5:00 PM → 6:00 PM   小學, 翰林, 英文  Yes  60  PS1
10  黃紫薰_Selina    2023/02/12 4:00 PM → 5:00 PM   小學, 康軒, 英文  Yes  60  PS1
11  黃紫薰_Selina   2023/02/07 12:00 PM → 1:00 PM   小學, 康軒, 英文  Yes  60  PS1

In [20]:
Nov

          Name                            Date         Subs 學生來源   完成  時長 課程形式
0    曼真(Joyce)    2022/11/24 7:30 PM → 8:30 PM   英文, 高二, 龍騰   高洋  Yes  60  PS1
1    曼真(Joyce)    2022/11/10 7:30 PM → 8:30 PM   英文, 高二, 龍騰   高洋  Yes  60  PS1
2    曼真(Joyce)    2022/11/21 7:30 PM → 8:30 PM   英文, 高二, 龍騰   高洋  Yes  60  PS1
3    曼真(Joyce)    2022/11/04 2:00 PM → 3:00 PM   英文, 高二, 龍騰   高洋  Yes  60  PS1
4    曼真(Joyce)    2022/11/07 7:30 PM → 8:30 PM   英文, 高二, 龍騰   高洋  Yes  60  PS1
5   李冠郁_Thomas  2022/11/13 10:30 AM → 12:00 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
6   李冠郁_Thomas  2022/11/20 10:30 AM → 12:00 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
7   李冠郁_Thomas  2022/11/06 10:30 AM → 12:00 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
8   李冠郁_Thomas  2022/11/27 10:30 AM → 12:00 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
9          羅英綺   2022/11/27 8:30 PM → 10:00 PM   英文, 高二, 龍騰   高洋  Yes  90  PS1
10         羅英綺    2022/11/29 5:00 PM → 6:30 PM   英文, 高二, 龍騰   高洋  Yes  90  PS1
11         羅英綺    2022/11/13 7:00 PM → 8:30 PM   英文, 高二, 龍騰   高洋  Yes  90  PS1
12     鈺淮_Josh    2022/11/21 7:00 PM → 8:30 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
13     鈺淮_Josh    2022/11/24 7:00 PM → 8:30 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
14     鈺淮_Josh    2022/11/28 7:00 PM → 8:30 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
15     鈺淮_Josh    2022/11/07 7:00 PM → 8:30 PM  國三, 總複習, 英文   高洋  Yes  90  PS1
16    黃學承_Matt    2022/11/27 8:30 PM → 9:30 PM   小學, 翰林, 英文   高洋  Yes  60  PS1
17    黃學承_Matt    2022/11/13 8:30 PM → 9:30 PM   小學, 翰林, 英文   高洋  Yes  60  PS1
18    黃學承_Matt    2022/11/06 8:30 PM → 9:30 PM   小學, 翰林, 英文   高洋  Yes  60  PS1
19    黃學承_Matt    2022/11/20 8:30 PM → 9:30 PM   小學, 翰林, 英文   高洋  Yes  60  PS1
20  黃紫薰_Selina    2022/11/24 8:30 PM → 9:30 PM   小學, 康軒, 英文   高洋  Yes  60  PS1
21  黃紫薰_Selina    2022/11/17 8:30 PM → 9:30 PM   小學, 康軒, 英文   高洋  Yes  60  PS1
22  黃紫薰_Selina    2022/11/10 8:30 PM → 9:30 PM   小學, 康軒, 英文   高洋  Yes  60  PS1
23  黃紫薰_Selina    2022/11/03 8:30 PM → 9:30 PM   小學, 康軒, 英文   高洋  Yes  60  PS1

In [21]:
#列出子集合
set_Feb = set(Feb["Name"])
set_Nov = set(Nov["Name"])

In [22]:
set_Feb

{'李冠郁_Thomas', '羅英綺', '鈺淮_Josh', '黃學承_Matt', '黃紫薰_Selina'}

In [23]:
set_Nov

{'曼真(Joyce)', '李冠郁_Thomas', '羅英綺', '鈺淮_Josh', '黃學承_Matt', '黃紫薰_Selina'}

In [24]:
#聯集:union
#全部的學生名稱
union = set_Feb | set_Nov
union

{'曼真(Joyce)', '李冠郁_Thomas', '羅英綺', '鈺淮_Josh', '黃學承_Matt', '黃紫薰_Selina'}

In [25]:
#交集:intersection
#從11月份持續上課到2月份的學生
intersection = set_Nov & set_Feb
intersection

{'李冠郁_Thomas', '羅英綺', '鈺淮_Josh', '黃學承_Matt', '黃紫薰_Selina'}

In [26]:
#差集:subtract1
#11月有上課，但沒有持續上課到2月份的學生
subtract1 = set_Nov - intersection
subtract1

{'曼真(Joyce)'}

In [28]:
#差集:subtract2
#11月沒有上課但在2月份新加入的學生
subtract2 = set_Feb - intersection
subtract2

set()

In [29]:
#對稱差集symmetric_difference
#新加入的學生或退出的學生
symmetric_difference = union - intersection 
symmetric_difference

{'曼真(Joyce)'}